// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231206135708_updateUser")]
    partial class updateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 12, 6, 15, 57, 8, 475, DateTimeKind.Local).AddTicks(5084),
                            Details = "im negan",
                            ImageUrl = "",
                            Name = "Test",
                            Occupancy = 5,
                            Rate = 3.0,
                            Sqft = 4,
                            UpdateDate = new DateTime(2023, 12, 6, 13, 57, 8, 475, DateTimeKind.Utc).AddTicks(5149)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 12, 6, 15, 57, 8, 475, DateTimeKind.Local).AddTicks(5153),
                            Details = "im Mahmoud",
                            ImageUrl = "",
                            Name = "Testing",
                            Occupancy = 3,
                            Rate = 4.0,
                            Sqft = 5,
                            UpdateDate = new DateTime(2023, 12, 6, 13, 57, 8, 475, DateTimeKind.Utc).AddTicks(5155)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 12, 6, 15, 57, 8, 475, DateTimeKind.Local).AddTicks(5158),
                            Details = "negan",
                            ImageUrl = "",
                            Name = "software",
                            Occupancy = 7,
                            Rate = 9.0,
                            Sqft = 8,
                            UpdateDate = new DateTime(2023, 12, 6, 13, 57, 8, 475, DateTimeKind.Utc).AddTicks(5161)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
